/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
	"./assets/**/*.js",
	"./templates/**/*.html.twig",
	],
	theme: {
		extend: {
			colors: {
				light: "var(--color-light)",
				medium: "var(--color-medium)",
				dark: "var(--color-dark)",
				light0: "var(--color-light-0)",
				medium0: "var(--color-medium-0)",
				dark0: "var(--color-dark-0)",
				light1: "var(--color-light-1)",
				medium1: "var(--color-medium-1)",
				dark1: "var(--color-dark-1)",
				light2: "var(--color-light-2)",
				medium2: "var(--color-medium-2)",
				dark2: "var(--color-dark-2)",
				light3: "var(--color-light-3)",
				medium3: "var(--color-medium-3)",
				dark3: "var(--color-dark-3)",
				light4: "var(--color-light-4)",
				medium4: "var(--color-medium-4)",
				dark4: "var(--color-dark-4)",
				light5: "var(--color-light-5)",
				medium5: "var(--color-medium-5)",
				dark5: "var(--color-dark-5)",
				light6: "var(--color-light-6)",
				medium6: "var(--color-medium-6)",
				dark6: "var(--color-dark-6)",
				light7: "var(--color-light-7)",
				medium7: "var(--color-medium-7)",
				dark7: "var(--color-dark-7)",
				light8: "var(--color-light-8)",
				medium8: "var(--color-medium-8)",
				dark8: "var(--color-dark-8)",
				light9: "var(--color-light-9)",
				medium9: "var(--color-medium-9)",
				dark9: "var(--color-dark-9)",
				light10: "var(--color-light-10)",
				medium10: "var(--color-medium-10)",
				dark10: "var(--color-dark-10)",
				light11: "var(--color-light-11)",
				medium11: "var(--color-medium-11)",
				dark11: "var(--color-dark-11)",
				light12: "var(--color-light-12)",
				medium12: "var(--color-medium-12)",
				dark12: "var(--color-dark-12)",
			},
		},
	},
	plugins: [],
	safelist: [
		{
			pattern: /(bg|fill|stroke|text|border|outline)-(light|medium|dark)+/,
			variants: ['hover', 'peer-checked', 'focus-within', 'data'],
		},
	]
}
